version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Build started on `date`...
      - npm install
  build:
    commands:
      - echo Build Phase running
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - appspec.yml